name: Publish Latest Docker image
on:
  push:
    branches:
      - "main"
  schedule:
    - cron: '0 0 * * 0'
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          platforms: linux/amd64, linux/arm64, linux/armv7
          tags: "latest, ${{ GITHUB_SHA }}"
