name: Publish Latest Docker image
on:
  push:
    branches:
      - "main"
  schedule:
    - cron: '0 0 * * 0'
jobs:
  push_to_registry:
    environment: docker_build
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          tags: |
            ghcr.io/eifoen/alpine-texlive/alpine-texlive:latest
            ghcr.io/eifoen/alpine-texlive/alpine-texlive:${{ github.sha }}
          push: true
